/**
 * ngDesk_Operations
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NgDeskOperations) {
      root.NgDeskOperations = {};
    }
    root.NgDeskOperations.Attachment = factory(root.NgDeskOperations.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Attachment model module.
   * @module model/Attachment
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Attachment</code>.
   * @alias module:model/Attachment
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Attachment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Attachment} obj Optional instance to populate.
   * @return {module:model/Attachment} The populated <code>Attachment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('FILE_NAME')) {
        obj['FILE_NAME'] = ApiClient.convertToType(data['FILE_NAME'], 'String');
      }
      if (data.hasOwnProperty('FILE_EXTENSION')) {
        obj['FILE_EXTENSION'] = ApiClient.convertToType(data['FILE_EXTENSION'], 'String');
      }
      if (data.hasOwnProperty('FILE')) {
        obj['FILE'] = ApiClient.convertToType(data['FILE'], 'String');
      }
      if (data.hasOwnProperty('TICKET_ATTACHMENT_UUID')) {
        obj['TICKET_ATTACHMENT_UUID'] = ApiClient.convertToType(data['TICKET_ATTACHMENT_UUID'], 'Number');
      }
      if (data.hasOwnProperty('COMPANY_ID')) {
        obj['COMPANY_ID'] = ApiClient.convertToType(data['COMPANY_ID'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} FILE_NAME
   */
  exports.prototype['FILE_NAME'] = undefined;
  /**
   * @member {String} FILE_EXTENSION
   */
  exports.prototype['FILE_EXTENSION'] = undefined;
  /**
   * @member {String} FILE
   */
  exports.prototype['FILE'] = undefined;
  /**
   * @member {Number} TICKET_ATTACHMENT_UUID
   */
  exports.prototype['TICKET_ATTACHMENT_UUID'] = undefined;
  /**
   * @member {String} COMPANY_ID
   */
  exports.prototype['COMPANY_ID'] = undefined;



  return exports;
}));


