/**
 * ngDesk_Operations
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NgDeskOperations) {
      root.NgDeskOperations = {};
    }
    root.NgDeskOperations.Reminder = factory(root.NgDeskOperations.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Reminder model module.
   * @module model/Reminder
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Reminder</code>.
   * @alias module:model/Reminder
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Reminder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reminder} obj Optional instance to populate.
   * @return {module:model/Reminder} The populated <code>Reminder</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TICKET_REMINDER_ID')) {
        obj['TICKET_REMINDER_ID'] = ApiClient.convertToType(data['TICKET_REMINDER_ID'], 'Number');
      }
      if (data.hasOwnProperty('TICKET_ID')) {
        obj['TICKET_ID'] = ApiClient.convertToType(data['TICKET_ID'], 'Number');
      }
      if (data.hasOwnProperty('INTERVAL')) {
        obj['INTERVAL'] = ApiClient.convertToType(data['INTERVAL'], 'Number');
      }
      if (data.hasOwnProperty('RECURRENCE')) {
        obj['RECURRENCE'] = ApiClient.convertToType(data['RECURRENCE'], 'Number');
      }
      if (data.hasOwnProperty('TYPE')) {
        obj['TYPE'] = ApiClient.convertToType(data['TYPE'], 'String');
      }
      if (data.hasOwnProperty('DATE_CREATED')) {
        obj['DATE_CREATED'] = ApiClient.convertToType(data['DATE_CREATED'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} TICKET_REMINDER_ID
   */
  exports.prototype['TICKET_REMINDER_ID'] = undefined;
  /**
   * @member {Number} TICKET_ID
   */
  exports.prototype['TICKET_ID'] = undefined;
  /**
   * @member {Number} INTERVAL
   */
  exports.prototype['INTERVAL'] = undefined;
  /**
   * @member {Number} RECURRENCE
   */
  exports.prototype['RECURRENCE'] = undefined;
  /**
   * @member {String} TYPE
   */
  exports.prototype['TYPE'] = undefined;
  /**
   * @member {String} DATE_CREATED
   */
  exports.prototype['DATE_CREATED'] = undefined;



  return exports;
}));


