/**
 * ngDesk_Operations
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Attachment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Attachment'));
  } else {
    // Browser globals (root is window)
    if (!root.NgDeskOperations) {
      root.NgDeskOperations = {};
    }
    root.NgDeskOperations.TicketMessage = factory(root.NgDeskOperations.ApiClient, root.NgDeskOperations.Attachment);
  }
}(this, function(ApiClient, Attachment) {
  'use strict';




  /**
   * The TicketMessage model module.
   * @module model/TicketMessage
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>TicketMessage</code>.
   * @alias module:model/TicketMessage
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>TicketMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TicketMessage} obj Optional instance to populate.
   * @return {module:model/TicketMessage} The populated <code>TicketMessage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TICKET_MESSAGE_ID')) {
        obj['TICKET_MESSAGE_ID'] = ApiClient.convertToType(data['TICKET_MESSAGE_ID'], 'Number');
      }
      if (data.hasOwnProperty('TICKET_ID')) {
        obj['TICKET_ID'] = ApiClient.convertToType(data['TICKET_ID'], 'Number');
      }
      if (data.hasOwnProperty('BODY')) {
        obj['BODY'] = ApiClient.convertToType(data['BODY'], 'String');
      }
      if (data.hasOwnProperty('USER_ID')) {
        obj['USER_ID'] = ApiClient.convertToType(data['USER_ID'], 'Number');
      }
      if (data.hasOwnProperty('DATE_CREATED')) {
        obj['DATE_CREATED'] = ApiClient.convertToType(data['DATE_CREATED'], 'Date');
      }
      if (data.hasOwnProperty('COMPANY_ID')) {
        obj['COMPANY_ID'] = ApiClient.convertToType(data['COMPANY_ID'], 'Number');
      }
      if (data.hasOwnProperty('TICKET_ATTACHMENTS')) {
        obj['TICKET_ATTACHMENTS'] = ApiClient.convertToType(data['TICKET_ATTACHMENTS'], [Attachment]);
      }
      if (data.hasOwnProperty('element1')) {
        obj['element1'] = ApiClient.convertToType(data['element1'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} TICKET_MESSAGE_ID
   */
  exports.prototype['TICKET_MESSAGE_ID'] = undefined;
  /**
   * @member {Number} TICKET_ID
   */
  exports.prototype['TICKET_ID'] = undefined;
  /**
   * @member {String} BODY
   */
  exports.prototype['BODY'] = undefined;
  /**
   * @member {Number} USER_ID
   */
  exports.prototype['USER_ID'] = undefined;
  /**
   * @member {Date} DATE_CREATED
   */
  exports.prototype['DATE_CREATED'] = undefined;
  /**
   * @member {Number} COMPANY_ID
   */
  exports.prototype['COMPANY_ID'] = undefined;
  /**
   * @member {Array.<module:model/Attachment>} TICKET_ATTACHMENTS
   */
  exports.prototype['TICKET_ATTACHMENTS'] = undefined;
  /**
   * @member {String} element1
   */
  exports.prototype['element1'] = undefined;



  return exports;
}));


